title: Tony Le
description: "This is the website you go to if you want to know who Tony Le is." 
url: "https://tonyle.com" 
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3

# Upper right corner of every page
aux_links:
  "Tony Le on GitHub":
    - "https://github.com/tfle/"
# Bottom right corner of every page
search.button: true
