title: Tony Le
description: This is the website you go to if you want to know who Tony Le is.
url: "https://tonyle.com" 
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3

# Upper right corner of every page
aux_links:
  "contact@tonyle.com":
    - "mailto:contact@tonyle.com"
# Bottom right corner of every page
search:
  button: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/tfle/personal-website"
gh_edit_branch: "main"
gh_edit_view_mode: "edit" # "tree" or "edit" to jump into the editor immediately

callouts_level: quiet # or loud
callouts:
  selected-user:
    title: Selected user
    color: purple
  hint:
    title: Hint
    color: blue
  did-you-know:
    title: Did you know?
    color: green
  task:
    title: Task
    color: purple
  warning:
    title: Warning
    color: red
