title: Tony Le
description: "This is the website you go to if you want to know who Tony Le is." 
url: "https://tonyle.com" 
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3

# Upper right corner of every page
aux_links:
  "contact@tonyle.com":
    - "mailto:contact@tonyle.com"
# Bottom right corner of every page
search:
  button: true

callouts_level: quiet # or loud
callouts:
  selected-user:
    title: Selected user
    color: purple
  hint:
    title: Hint
    color: blue
  did-you-know:
    title: Did you know?
    color: green
  task:
    title: Task
    color: purple
  warning:
    title: Warning
    color: red
