title: Tony Le
description: >-
  I am a Master of Information Technology student at the University of New South Wales.
  Previously, I completed degrees in Physics and Medical Science at the University of Sydney.
  This website is mostly home to a hodgepodge of code and documentation written for future reference.
url: "https://tonyle.com" 
search_enabled: false
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
