title: Tony Le
description: "This is the website you go to if you want to know who Tony Le is." 
url: "https://tonyle.com" 
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3

# Upper right corner of every page
aux_links:
  "Tony Le on GitHub":
    - "https://github.com/tfle/"
# Bottom right corner of every page
search.button: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
